### ISSUE TITLE
Send user and rooms highlights aka pills

### ISSUE THREAD

**Issue by farribeiro** [cinnyapp/cinny#19]
**Is your feature request related to a problem? Please describe.**
This issue is related #18. Plain text. The user isn't formmated neither other clients.

**Describe the solution you'd like**
the messages in matrix arrives in two way, with/without html. 

**Describe alternatives you've considered**
None.

**Additional context**
Like #cinny:matrix.org should be a link.

**Comment by farribeiro** [comment]
I forget to add room highlights too

**Comment by kfiven** [comment]
https://spec.matrix.org/unstable/client-server-api/#user-room-and-group-mentions
