### ISSUE TITLE
Feature request: Change and recovery password

### ISSUE THREAD

**Issue by farribeiro** [cinnyapp/cinny#26]
**Is your feature request related to a problem? Please describe.**
The client doesn't have to change or recovery the password

**Describe the solution you'd like**
Implements on the settings to do that actions 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Domoel** [comment]
why is this still open? :-(

**Comment by Yatekii** [comment]
I still don't see any option to change the password.

**Comment by ajbura** [comment]
@Yatekii it's on the auth screen https://app.cinny.in/reset-password/matrix.org (you can open it in incognito tab

**Comment by Yatekii** [comment]
That requires an email to be set. But the email also can't be set/changed, so this is still a but unwieldy. In FluffyChat I can explicitely change the PW in the settings for example.

**Comment by Henry-Hiles** [comment]
Yeah, being able to change the password in settings would be ideal.
