### ISSUE TITLE
Being able to open images without having to open them in a new tab

### ISSUE THREAD

**Issue by not-a-dev-stein** [cinnyapp/cinny#5]
**Is your feature request related to a problem? Please describe.**
The only way to view sent images right now is to either download them or open them in a new tab, which is quite unintuitive, specially for new users. They are great as secondary options, but should not be the primary way to interact with them.

**Describe the solution you'd like**
The app should at least open them in a lightbox when clicking on the image itself, opening it in a pop-up that could be closed either by clicking on a "close" button or by clicking outside of the pop-up box.

**Comment by menturion** [comment]
I also think that it is best practice to open images in a new layer instead of a new tab. This feels a bit like Web 1.0.

**Comment by arnopensource** [comment]
@C0ffeeCode spoke of pdf too, I don't know if it needs another issue ?

**Comment by ajbura** [comment]
related #181
