### ISSUE TITLE
Make the app responsive

### ISSUE THREAD

**Issue by ajbura** [cinnyapp/cinny#55]
#### Is your feature request related to a problem? Please describe.
No

#### Describe the solution you'd like
Responsive interface for different devices.

**Comment by farribeiro** [comment]
I think this issue resolves #17

**Comment by daemonspring** [comment]
This is also relevant to desktop users. I have a second monitor in a portrait orientation (1080x1920) and it'd be the ideal place to move the chat to. Cinny doesn't handle that limited width at the moment.

**Comment by samueldr** [comment]
Collapsing the left panel would help, I think. I'm slowly working out *opinionated* changes in the user interface for better information density, and have been playing with a scheme where the left sidebar is collapsed until hovered over.

![image](https://user-images.githubusercontent.com/132835/140995219-30e3ba2b-0f70-4bad-81cf-b43009beb009.png)

(This screenshot includes more WIP features than strictly the collapsible side-bar.)

I *think* it shouldn't be too hard to cleanup and add as a setting option. Though at the current time it's not ready for general use.

If you want to try it out, you can use the following:

 - https://gist.github.com/8bf14929d5b550b0e5ea86ed31379d33

It *may* work as a stylus style if you use the options to pre-process with sass.

**Comment by N-R-K** [comment]
> have been playing with a scheme where the left sidebar is collapsed until hovered over.

I personally don't like this type of UI. It's one of the things I *hated* about element. When I collapse the sidebar, I want it to *stay* collapsed. But element opens it up on window resize and I have to manually collapse it again.

**Comment by samueldr** [comment]
> I personally don't like this type of UI. It's one of the things I _hated_ about element. When I collapse the sidebar, I want it to _stay_ collapsed. But element opens it up on window resize and I have to manually collapse it again.

Note that it stays collapsed even when the window is expanded. It's only *when interacting with the sidebar* that it expands. Note that in this WIP implementation it expands *without disrupting the layout*, there is no reflow of the window contents.

I think I have the same grievances against element's "collapsible" panels. I was always fighting against them. Always wanting them to stay collapsed when they didn't. And also importantly, forced to uncollapse for complex interactions.

Note that the expected implementation would make this *optional*, so people that don't like collapsed panels shouldn't be affected by default.

**Comment by vwkd** [comment]
Any updates on this? Currently Cinny is unusable on mobile.

Cinny could be the one modern responsive PWA matrix client. Advantages are many, like being able to move faster because of a single code base instead of multiple for each native platform. Also (distant) future proof since with the (admittedly slow) advent of WASI and GPU rendering support native apps will likely be a thing of the past as a single WebAssembly app runs everywhere.

**Comment by kfiven** [comment]
Sub-issues:
[ ] #743 
[ ] #736 
[ ] #566 
[ ] #567

**Comment by kubo6472** [comment]
*Sub-issues: 

- [x] #743 
- [x] #736 
- [x] #566 
- [x] #567

@kfiven what's left to do, then?

**Comment by aceArt-GmbH** [comment]
Maybe https://github.com/cinnyapp/cinny/pull/1587 could be merged to improve mobile usage
