### ISSUE TITLE
Push responsive interface "depth" into JS history

### ISSUE THREAD

**Issue by hifi** [cinnyapp/cinny#70]
#### Is your feature request related to a problem? Please describe.
Browser back history is not currently populated at all. Though there's not much to populate right now.

#### Describe the solution you'd like
For immersive PWA/wrapper mode the browser back action needs to do a logical "go back" event within the application. This can then be used with an Android wrapper to let soft back button events to bubble within the application until there are no more back events available in the browser history. The last soft back button event can finally be bound to close the application.

#### Describe alternatives you've considered
Back button will immediately close the application in PWA/wrapper mode. This could be better.

#### Additional context
Consider the max UI stack in responsive mode is something like this (after login):

`Spaces -> Rooms -> Room ->  People -> Profile`

Each layer should be pushed to browser history so back will go one step back every time it is pressed. There are different branches in the stack of course so this is only an example.

**Comment by jtrees** [comment]
I frequently find myself missing the "back" feature in the browser.

In my case I expect it to bring me to the last place I was, regardless of it's place in the app hierarchy though. For example, if I am in the "Direct Messages" pane and switch from Alice to Bob, then I expect to land back at Alice even though Alice and Bob have the same "depth" in the application hierarchy.
