### ISSUE TITLE
Custom Emoji & Stickers using MSC2545

### ISSUE THREAD

**Issue by BBaoVanC** [cinnyapp/cinny#83]
#### Describe the solution you'd like

Currently [MSC2545](https://github.com/matrix-org/matrix-doc/pull/2545) is completely unsupported in Cinny. Emotes just show as the name, and stickers just show as regular images. It would be nice to be able to properly view and send custom stickers and emoji using Cinny.

#### Additional context

MSC2545 is currently supported in Nheko and FluffyChat. It allows you to create sticker/emoji packs which can be added to your user, or to rooms.

**Comment by ajbura** [comment]
Hi, how can I test them in FluffyChat? I have tried to add some custom emojis, but it doesn't seems to wrok?

**Comment by BBaoVanC** [comment]
> Hi, how can I test them in FluffyChat? I have tried to add some custom emojis, but it doesn't seems to wrok?

You can press the plus on the chat box, then "Send sticker", or you can type a colon and then start typing the name of the emote (ex. `:cat` will show custom emoji starting with "cat"). There's also an emote pack in the FluffyChat room with a single FluffyChat sticker, and I also have some in my room ([#general:boba.best](https://matrix.to/#/#general:boba.best)).

**Comment by jasikpark** [comment]
In testing element still doesn't have support, but Nheko Reborn has both room level support, globally adding emoji packs, and uploading your own available

but QT D:

**Comment by licentiapoetica** [comment]
I noticed that the stickers/emojis appear in cinny when you have added them in nheko for example but don't get rendered in the message
